# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: joamit
description: > # this means to ignore newlines until "baseurl:"
  Personal webpage
repository: https://github.com/joamit/joamit.github.io
baseurl: https://joamit.github.io  # the subpath of your site, e.g. /blog
url: https://joamit.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: amit.joshi
email: amitjoshiave@gmail.com

navigation:
  - text: Home
    url: /
  - text: Resume
    url: /resume
  - text: Projects
    url: /projects

projects:
  - name: angular-snake
    description: AngularJS based Classic Snake Game.
    link: https://github.com/joamit/snakey
    image: https://github.com/joamit/joamit.github.io/blob/master/images/2017-05-08-xml.png

social:
  - service: github
    username: joamit
    link: https://github.com/joamit
  - service: twitter
    username: lifeboundamit
    link: https://twitter.com/lifeboundamit

# Plugins
gems:
  - jekyll-seo-tag
